[project]
name = "gfont"
version="0.0.8"
description = "Browse and install fonts from fonts.google.com"
readme = "README.md"
authors = [
    { name = "Phyo Wai Lin", email="phyowailin2004@proton.me" }
]
keywords = ["font", "google"]
license = { file = "LICENSE" }
classifiers = [
    "Environment :: Console",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Topic :: System :: Console Fonts",
    "Topic :: Text Processing :: Fonts"
]
dependencies = [
    "requests"
]

[project.scripts]
gfont = "gfont:main"

[tool.poetry]
name = "gfont"
version="0.0.8"
authors = [
    "Phyo Wai Lin <phyowailin2004@proton.me>"
]
description = "Browse and install fonts from fonts.google.com"

[tool.poetry.dependencies]
python = "^3.8"
requests = "*"

[tool.poetry.group.dev.dependencies]
black = "*"
pre-commit = "*"
isort = "*"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ["py38"]

[tool.isort]
multi_line_output = 3
combine_as_imports = true
include_trailing_comma = true
force_grid_wrap = 3
ensure_newline_before_comments = true
