[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gfont"
description=  "Browse and install fonts from fonts.google.com"
version = "0.0.4"
readme = "README.md"
keywords = ["font", "google"]
license = { file = "LICENSE" }
dependencies = ["requests"]
requires-python = ">=3.8"
classifiers = [
    "Environment :: Console",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Topic :: System :: Console Fonts",
    "Topic :: Text Processing :: Fonts",
]

[project.scripts]
gfont = "gfont:main"

[tool.setuptools]
packages = ["gfont"]