[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gfont"
description=  "Browse and install fonts from fonts.google.com"
version = "0.0.2"
readme = "README.md"
keywords = ["font", "google"]
license = { file = "LICENSE" }
dependencies = ["requests"]
requires-python = ">=3.8"

[project.scripts]
gfont = "gfont.cli:main"